//  <autogenerated>
//      This code was generated by a tool.
//      Xamarin Excalibur Version: 1.0.6400.27431
//  </autogenerated>

// 
// Copyright (c) 2013 Xamarin Inc. (http://www.xamarin.com)
// 
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
// 
// The above copyright notice and this permission notice shall be included in
// all copies or substantial portions of the Software.
// 
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
// THE SOFTWARE.
// 

[assembly: System.Runtime.CompilerServices.TypeForwardedToAttribute(typeof(Mono.Security.Interface.Alert))]
[assembly: System.Runtime.CompilerServices.TypeForwardedToAttribute(typeof(Mono.Security.Interface.AlertDescription))]
[assembly: System.Runtime.CompilerServices.TypeForwardedToAttribute(typeof(Mono.Security.Interface.AlertLevel))]
[assembly: System.Runtime.CompilerServices.TypeForwardedToAttribute(typeof(Mono.Security.Interface.CertificateValidationHelper))]
[assembly: System.Runtime.CompilerServices.TypeForwardedToAttribute(typeof(Mono.Security.Interface.CipherAlgorithmType))]
[assembly: System.Runtime.CompilerServices.TypeForwardedToAttribute(typeof(Mono.Security.Interface.CipherSuiteCode))]
[assembly: System.Runtime.CompilerServices.TypeForwardedToAttribute(typeof(Mono.Security.Interface.ExchangeAlgorithmType))]
[assembly: System.Runtime.CompilerServices.TypeForwardedToAttribute(typeof(Mono.Security.Interface.HashAlgorithmType))]
[assembly: System.Runtime.CompilerServices.TypeForwardedToAttribute(typeof(Mono.Security.Interface.ICertificateValidator))]
[assembly: System.Runtime.CompilerServices.TypeForwardedToAttribute(typeof(Mono.Security.Interface.IMonoSslStream))]
[assembly: System.Runtime.CompilerServices.TypeForwardedToAttribute(typeof(Mono.Security.Interface.MonoEncryptionPolicy))]
[assembly: System.Runtime.CompilerServices.TypeForwardedToAttribute(typeof(Mono.Security.Interface.MonoLocalCertificateSelectionCallback))]
[assembly: System.Runtime.CompilerServices.TypeForwardedToAttribute(typeof(Mono.Security.Interface.MonoRemoteCertificateValidationCallback))]
[assembly: System.Runtime.CompilerServices.TypeForwardedToAttribute(typeof(Mono.Security.Interface.MonoSslPolicyErrors))]
[assembly: System.Runtime.CompilerServices.TypeForwardedToAttribute(typeof(Mono.Security.Interface.MonoTlsConnectionInfo))]
[assembly: System.Runtime.CompilerServices.TypeForwardedToAttribute(typeof(Mono.Security.Interface.MonoTlsProvider))]
[assembly: System.Runtime.CompilerServices.TypeForwardedToAttribute(typeof(Mono.Security.Interface.MonoTlsProviderFactory))]
[assembly: System.Runtime.CompilerServices.TypeForwardedToAttribute(typeof(Mono.Security.Interface.MonoTlsSettings))]
[assembly: System.Runtime.CompilerServices.TypeForwardedToAttribute(typeof(Mono.Security.Interface.TlsException))]
[assembly: System.Runtime.CompilerServices.TypeForwardedToAttribute(typeof(Mono.Security.Interface.TlsProtocolCode))]
[assembly: System.Runtime.CompilerServices.TypeForwardedToAttribute(typeof(Mono.Security.Interface.TlsProtocols))]
[assembly: System.Runtime.CompilerServices.TypeForwardedToAttribute(typeof(Mono.Security.Interface.ValidationResult))]

