//  <autogenerated>
//      This code was generated by a tool.
//      Xamarin Excalibur Version: 1.0.6109.14854
//  </autogenerated>

[assembly: System.Runtime.CompilerServices.TypeForwardedToAttribute(typeof(Mono.Btls.Interface.BtlsObject))]
[assembly: System.Runtime.CompilerServices.TypeForwardedToAttribute(typeof(Mono.Btls.Interface.BtlsProvider))]
[assembly: System.Runtime.CompilerServices.TypeForwardedToAttribute(typeof(Mono.Btls.Interface.BtlsX509))]
[assembly: System.Runtime.CompilerServices.TypeForwardedToAttribute(typeof(Mono.Btls.Interface.BtlsX509Chain))]
[assembly: System.Runtime.CompilerServices.TypeForwardedToAttribute(typeof(Mono.Btls.Interface.BtlsX509Error))]
[assembly: System.Runtime.CompilerServices.TypeForwardedToAttribute(typeof(Mono.Btls.Interface.BtlsX509Format))]
[assembly: System.Runtime.CompilerServices.TypeForwardedToAttribute(typeof(Mono.Btls.Interface.BtlsX509Lookup))]
[assembly: System.Runtime.CompilerServices.TypeForwardedToAttribute(typeof(Mono.Btls.Interface.BtlsX509Name))]
[assembly: System.Runtime.CompilerServices.TypeForwardedToAttribute(typeof(Mono.Btls.Interface.BtlsX509Purpose))]
[assembly: System.Runtime.CompilerServices.TypeForwardedToAttribute(typeof(Mono.Btls.Interface.BtlsX509Store))]
[assembly: System.Runtime.CompilerServices.TypeForwardedToAttribute(typeof(Mono.Btls.Interface.BtlsX509StoreCtx))]
[assembly: System.Runtime.CompilerServices.TypeForwardedToAttribute(typeof(Mono.Btls.Interface.BtlsX509StoreManager))]
[assembly: System.Runtime.CompilerServices.TypeForwardedToAttribute(typeof(Mono.Btls.Interface.BtlsX509StoreType))]
[assembly: System.Runtime.CompilerServices.TypeForwardedToAttribute(typeof(Mono.Btls.Interface.BtlsX509TrustKind))]
[assembly: System.Runtime.CompilerServices.TypeForwardedToAttribute(typeof(Mono.Btls.Interface.BtlsX509VerifyFlags))]
[assembly: System.Runtime.CompilerServices.TypeForwardedToAttribute(typeof(Mono.Btls.Interface.BtlsX509VerifyParam))]
[assembly: System.Runtime.CompilerServices.TypeForwardedToAttribute(typeof(Mono.Btls.Interface.VersionInfo))]

